### ISSUE TITLE
Example of structured message with text

### ISSUE THREAD

**Issue by Naktibalda** [codeforequity-at/testmybot#24]
[README](https://github.com/codeforequity-at/testmybot#structured-messages) and [tests](https://github.com/codeforequity-at/testmybot/blob/master/samples/botkit/jasmine/spec/convo/structured.convo.txt) contain 2 very specific examples of structures messages:
* with attachments
* with postback

I want to send a structured messages containing text and one more more attributes,
example:
```js
#bot
{
    "message": {
        "text": "Thanks, so you want to pay £34.56, please enter your details",
        "action": "take_payment"
    }
}
```

When I run this convo, I get error "TypeError: convomsg.msg.split is not a function".
What is a correct format?

**Comment by codeforequity-at** [comment]
The format should be correct, but I noticed a bug in there.

lib/testbuilder.js, line 31ff is bad coding.
Happens when bot sends a text message while test case expects structured message.

What does the console output tell ? Should match this behaviour.
If not, there may be another problem, but this is a bug for sure.
